"""Slug field added to recipe

Revision ID: 0e63e48c60b4
Revises: 655909472860
Create Date: 2025-06-28 20:57:29.955544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e63e48c60b4'
down_revision: Union[str, None] = '655909472860'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('slug', sa.String(), nullable=True))
    op.create_index(op.f('ix_recipes_slug'), 'recipes', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recipes_slug'), table_name='recipes')
    op.drop_column('recipes', 'slug')
    # ### end Alembic commands ###
