"""Add calorie fields to Recipe

Revision ID: 655909472860
Revises: e11cbb707e8c
Create Date: 2025-06-26 21:18:07.026546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '655909472860'
down_revision: Union[str, None] = 'e11cbb707e8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('estimated_weight_g', sa.Integer(), nullable=True))
    op.add_column('recipes', sa.Column('total_calories_per_100g', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'total_calories_per_100g')
    op.drop_column('recipes', 'estimated_weight_g')
    # ### end Alembic commands ###
