"""admin field updated

Revision ID: 9a6587d865d1
Revises: cb22587d6681
Create Date: 2025-07-01 20:50:47.462749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a6587d865d1'
down_revision: Union[str, None] = 'cb22587d6681'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. Обновим все NULL значения в поле is_admin на False
    op.execute("UPDATE users SET is_admin = FALSE WHERE is_admin IS NULL")

    # 2. Теперь можно установить ограничение NOT NULL
    op.alter_column('users', 'is_admin',
        existing_type=sa.BOOLEAN(),
        nullable=False)



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
