"""remove ingredients column from recipe

Revision ID: e11cbb707e8c
Revises: 66565584b153
Create Date: 2025-06-26 16:11:38.929138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e11cbb707e8c'
down_revision: Union[str, None] = '66565584b153'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'ingredients')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('ingredients', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
