"""add halal, vegan to recipes

Revision ID: ec95e8148be3
Revises: 03c967d58c50
Create Date: 2025-07-23 15:57:31.991699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec95e8148be3'
down_revision: Union[str, None] = '03c967d58c50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('is_vegan', sa.Boolean(), nullable=True))
    op.add_column('recipes', sa.Column('is_halal', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'is_halal')
    op.drop_column('recipes', 'is_vegan')
    # ### end Alembic commands ###
