name: Next.js + FastAPI CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  nextjs:
    name: Next.js
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./frontend 

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build
  
  fastapi:
    name: FastAPI
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./back

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/prod.txt
        